dadi/publish

- dadi/frontend/lib/keyboard.js
- dadi/frontend/views/DocumentList/DocumentList.jsx
feat: Basic keyboard event lib
@eduardoboucas Still needs:
> feat: Create keyboard listeners

- dadi/frontend/lib/router.js
- dadi/frontend/views/DocumentList/DocumentList.jsx
Generating urls has never been easier
```html
<a href={createRoute({
params: {sort: sortBy, order: sortOrder}, 
update: true
})}>{value}</a>
```
> feat: generate url for anchors

- dadi/frontend/components/Button/Button.css
- dadi/frontend/components/Button/Button.jsx
- dadi/frontend/components/DocumentFilter/DocumentFilter.css
- dadi/frontend/components/DocumentFilter/DocumentFilter.jsx
- dadi/frontend/components/DocumentFilters/DocumentFilters.css
- dadi/frontend/components/DocumentFilters/DocumentFilters.jsx
- dadi/frontend/components/ListController/ListController.css
- dadi/frontend/components/ListController/ListController.jsx
- dadi/frontend/components/Main/Main.css
- dadi/frontend/components/TextInput/TextInput.jsx
- dadi/frontend/views/DocumentList/DocumentList.jsx
Also adds documentation to `DocumentFilters` and `DocumentFilter` components.
> Add styling to document list filters

- frontend/actions/documentActions.js
- frontend/actions/documentsActions.js
- frontend/components/Dropdown/Dropdown.css
- frontend/containers/App/App.jsx
- frontend/containers/CollectionNav/CollectionNav.jsx
- frontend/lib/app-config.js
- frontend/reducers/api.js
- frontend/views/DocumentEdit/DocumentEdit.jsx
- frontend/views/DocumentList/DocumentList.jsx
(Merging this into `feat/field-types`, so that all changes go in #84)
> Add support for multiple APIs

- frontend/components/FieldString/FieldString.jsx
- frontend/views/DocumentEdit/DocumentEdit.jsx
And remove random string from document edit view. Closes #89.
> Fix issue with full page reload

- docs/components/FieldImage.md
- frontend/components/FieldImage/FieldImage.jsx
- frontend/components/FieldImage/FieldImageConfigSchema.js
- frontend/containers/DocumentEdit/DocumentEdit.jsx
WIP!
feat: image data updated with onChange
feat: image data saving (currently as raw)
feat: reference fields located in document, ready to use with reference document create/update method
> feat: handle image upload

- frontend/actions/apiActions.js
- frontend/actions/documentActions.js
- frontend/actions/documentsActions.js
- frontend/actions/userActions.js
- frontend/containers/App/App.jsx
- frontend/containers/DocumentEdit/DocumentEdit.jsx
- frontend/lib/api-bridge-client.js
> Load api version and database from collection, not config block

- frontend/containers/DocumentList/DocumentList.jsx
> Add message for empty filtered list

- .gitignore
- app/config-schema.js
- app/lib/controllers/api-bridge.js
- frontend/actions/documentActions.js
- frontend/components/DateTimePicker/DateTimePicker.jsx
- frontend/components/DocumentFilter/DocumentFilter.css
- frontend/components/DocumentFilter/DocumentFilter.jsx
- frontend/components/DocumentFilters/DocumentFilters.css
- frontend/components/DocumentFilters/DocumentFilters.jsx
- frontend/components/FieldBoolean/FieldBoolean.jsx
- frontend/components/FieldBoolean/FieldBooleanFilter.jsx
- frontend/components/FieldDateTime/FieldDateTime.jsx
- frontend/components/FieldDateTime/FieldDateTimeEdit.jsx
- frontend/components/FieldDateTime/FieldDateTimeFilter.jsx
- frontend/components/FieldImage/FieldImageEdit.jsx
- frontend/components/FieldNumber/FieldNumber.jsx
- frontend/components/FieldNumber/FieldNumberFilter.jsx
- frontend/components/FieldString/FieldString.jsx
- frontend/components/FieldString/FieldStringFilter.jsx
- frontend/containers/DocumentEdit/DocumentEdit.jsx
- frontend/containers/DocumentListController/DocumentListController.jsx
- frontend/containers/DocumentListToolbar/DocumentListToolbar.jsx
- frontend/containers/Header/Header.jsx
- frontend/lib/status.js
- frontend/lib/util/url-helper.js
- scripts/build-docs/generateMarkdown.js
feat: filters are now updated on return and on apply click
feat: filter inputs are updated on keyup
> feat: refractor filters

- frontend/components/FieldImage/FieldImageEdit.jsx
- frontend/components/FieldImage/FieldImageReferenceSelect.jsx
This PR implements a change to media in API, as described [in this comment](https://github.com/dadi/api/pull/247#issuecomment-302028226).
> Use url property for media objects

- frontend/actions/documentActions.js
- frontend/containers/DocumentEdit/DocumentEdit.jsx
- frontend/lib/local-storage.js
> Fix issue with discard changes

- frontend/containers/App/App.jsx
- frontend/lib/socket.js
@eduardoboucas this should fix the issue with sockets that causes a load of console errors on your local
> fix: socket port now taken from config

- app/lib/server/index.js
- package.json
Introduces a server restart method required for https://github.com/dadi/ssl/pull/3
> chore: change package reference

- app/config-schema.js
> Allow config file names to use custom env values

- app/config-schema.js
- docs/components/TextInputWithDatePicker.md
- frontend/components/FieldDateTime/FieldDateTimeFilter.jsx
- frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.css
- frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx
- test/unit/app/lib/controllers/app-config.test.js
> Make FieldDateTimeFilter use new TextInputWithDatePicker component

- app/config-schema.js
- app/lib/controllers/api-bridge.js
- app/lib/controllers/session.js
- app/lib/models/collection.js
- app/lib/router/index.js
- index.js
- package.json
- test/unit/app/lib/controllers/app-config.test.js
In this PR:
- feat: some basic logging
- refactor: middleware to replace restify request logging
- feat: logging config schema
- test: improved config schema coverage
- feat: router error and debug logging
- feat: api bridge error logging
> feat: add logging to session and bridge

- README.md
- app/config-schema.js
- frontend/components/FieldImage/FieldImageEdit.jsx
- frontend/components/FieldImage/FieldImageReferenceSelect.jsx
- frontend/containers/DocumentList/DocumentList.jsx
- scripts/coverage/coverage.svg
This PR:
- Adds config support for CDN publicUrl
- Extends the `getImageSrc` method to cover CDN urls
- Introduces `getImageSrc` into the Image Reference field component
- Passes config to all Reference components
> feat: support for CDN publicUrl

- app/lib/helpers/collection-routes.js
> Use generic document ID format

- docs/components/FileUpload.md
- frontend/components/FieldImage/FieldImage.css
- frontend/components/FieldImage/FieldImageEdit.jsx
- frontend/components/FieldImage/FieldImageEdit.test.jsx
- frontend/components/FileUpload/FileUpload.css
- frontend/components/FileUpload/FileUpload.jsx
> File upload button styling fixes

- README.md
- frontend/components/DateTimePicker/DateTimePicker.css
fix: increase datetimepicker z-index
Fix #359
> increase datetimepicker z-index

- frontend/actions/documentsActions.js
> fix: add default sort per collection

- README.md
- frontend/components/Dropdown/Dropdown.css
> fix: dropdown navs now have a higher z-index than the menu items they came from

- frontend/components/NavItem/NavItem.css
Make dropdowns above other menu items! Should fix #305
> fix: menu z-index

- frontend/containers/DocumentListToolbar/DocumentListToolbar.css
- frontend/containers/DocumentListToolbar/DocumentListToolbar.jsx
> Make go to page input field more narrow

- frontend/containers/DocumentEdit/DocumentEdit.css
> CSS alignment fixes

- frontend/components/Button/Button.css
- frontend/components/Button/Button.jsx
- frontend/components/ListController/ListController.css
- frontend/components/ListController/ListController.jsx
- frontend/containers/DocumentListController/DocumentListController.jsx
> display collection name on index view

- frontend/containers/CollectionNav/CollectionNav.jsx
> sort menu items according to config file

- docs/components/TextInput.md
- docs/components/TextInputWithDatePicker.md
- frontend/components/TextInput/TextInput.jsx
- frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx
- frontend/containers/SignIn/SignIn.css
- frontend/containers/SignIn/SignIn.jsx
> Fix validation issues on sign-in form

- frontend/containers/DocumentList/DocumentList.jsx
> Gracefully handle invalid route

- docs/containers/ProfileEdit.md
- frontend/components/FieldReference/FieldReference.css
- frontend/components/FieldReference/FieldReferenceEdit.jsx
- frontend/reducers/api.js
- frontend/views/DocumentEditView/DocumentEditView.jsx
> Add links to referenced documents

- frontend/containers/DocumentEditToolbar/DocumentEditToolbar.jsx
- frontend/views/DocumentCreateView/DocumentCreateView.jsx
+ fix issue where the URL is not updated when creating a new docuiment
> Hide Delete button when creating a new document

- frontend/containers/ProfileEditToolbar/ProfileEditToolbar.jsx
> Stop showing profile updated message when validation errors are present

- frontend/containers/DocumentListToolbar/DocumentListToolbar.jsx
- frontend/views/DocumentListView/DocumentListView.jsx
This PR attempts to fix pagination.
Fix #475
> Pass page number to url builder

- frontend/components/TextInput/TextInput.jsx
> fix: textbox flash fix

- frontend/components/FieldImage/FieldImage.css
- frontend/components/FieldImage/FieldImage.jsx
- frontend/components/FieldImage/FieldImageList.jsx
- frontend/components/FieldReference/FieldReference.css
- frontend/components/FieldReference/FieldReference.jsx
- frontend/components/FieldReference/FieldReferenceList.jsx
- frontend/containers/DocumentList/DocumentList.jsx
> Resolve reference fields in list view

- README.md
- frontend/components/FieldDateTime/FieldDateTimeEdit.jsx
- frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx
> Readonly datetime (part 2 - the saga continues)

- frontend/containers/CollectionNav/CollectionNav.jsx
> fix: always generate menu items

- app/config-schema.js
- app/lib/server/index.js
- index.js
Allows cmd+click to open the site from the terminal.
Close #499
> Add public url to boot message

- docs/components/ButtonWithOptions.md
- docs/components/FieldImageList.md
- docs/components/FieldReferenceList.md
- frontend/components/ButtonWithOptions/ButtonWithOptions.jsx
- frontend/containers/DocumentEditToolbar/DocumentEditToolbar.jsx
> Save the Save Options

- frontend/actions/apiActions.js
- frontend/actions/userActions.js
This should speed up the application startup process and hopefully make @paulrgn and everyone else feel happy about life in general (and Publish specifically).
Closes #503.
> Batch load API collections

- docs/components/FieldDateTimeEdit.md
- docs/components/FieldNumberEdit.md
- docs/components/FieldStringEdit.md
- frontend/components/FieldDateTime/FieldDateTimeEdit.jsx
- frontend/components/FieldNumber/FieldNumberEdit.jsx
- frontend/components/FieldString/FieldStringEdit.jsx
- frontend/containers/DocumentEdit/DocumentEdit.jsx
> Add field description option

- frontend/components/TextInput/TextInput.css
- frontend/components/TextInput/TextInput.jsx
> auto resize textarea

- frontend/containers/DocumentEditToolbar/DocumentEditToolbar.jsx
> Fix sign out error

- frontend/components/FieldString/FieldStringEdit.jsx
> Pass select box options to function

- frontend/containers/ProfileEdit/ProfileEdit.jsx
This PR adds a div with a data-field-name attribute around the profile edit fields, to assist with automated tests
> Add data-field attributes to profile edit

- frontend/containers/DocumentList/DocumentList.jsx
> Use field name as label in columns when no label specified

- frontend/components/TextInput/TextInput.jsx
- frontend/containers/DocumentEdit/DocumentEdit.jsx
- frontend/containers/SignIn/SignIn.jsx
This fixes issues with wrong fields being autofilled by the browser.
> Prevent TextInput component from being recycled

- frontend/components/RichEditor/RichEditor.css
- frontend/components/RichEditor/RichEditor.jsx
> Improve Link button in RichEditor

- frontend/components/RichEditor/RichEditor.css
> Remove outline on text mode button

- frontend/views/DocumentEditView/DocumentEditView.jsx
- frontend/views/DocumentListView/DocumentListView.jsx
> Remove filters from Create New link

- frontend/components/FieldNumber/FieldNumberEdit.jsx
- frontend/components/FieldNumber/FieldNumberFilter.jsx
- frontend/components/FieldPassword/FieldPasswordEdit.jsx
- frontend/components/FieldString/FieldStringEdit.jsx
- frontend/components/FieldString/FieldStringFilter.jsx
- frontend/components/TextInput/TextInput.jsx
- frontend/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx
- frontend/containers/SignIn/SignIn.jsx
- frontend/views/PasswordResetView/PasswordResetView.jsx
> Fix issues with changes to fields not being persisted

- frontend/components/RichEditor/RichEditor.jsx
> Make RichEditor broadcast null on empty values

- frontend/actions/routerActions.js
- frontend/containers/DocumentEdit/DocumentEdit.jsx
- frontend/lib/local-storage.js
- frontend/reducers/document.js
> Stop unsaved changes from leaking to different documents

- frontend/containers/DocumentList/DocumentList.jsx
- frontend/views/MediaListView/MediaListView.css
- frontend/views/MediaListView/MediaListView.jsx
> Fix delete action in media list view

- frontend/components/RichEditor/RichEditor.css
- frontend/components/RichEditor/RichEditor.jsx
@abovedave could you have a quick look and retest, please? 😇 
Closes #588
Closes #589
Closes #606
> Various fixes to RichEditor

- frontend/components/ColorPicker/ColorPicker.jsx
- frontend/components/FieldColor/FieldColorEdit.jsx
@jimlambie I was fixing another issue with the colour field, where an error was thrown when clicking on a colour field that didn't have a value, which in its turn may have fixed the issue with multiple colour pickers, since I can't replicate it. Are you able to test, please?
Closes #619.
> Fix issues with Color field

- frontend/components/RichEditor/RichEditor.jsx
> Fix toggling of code blocks in rich editor

- frontend/components/ButtonWithPrompt/ButtonWithPrompt.jsx
- frontend/views/MediaListView/MediaListView.jsx
> Show notification when media items are deleted from media list view

- frontend/components/DocumentFilters/DocumentFilters.jsx
- frontend/components/FieldString/FieldString.jsx
> Make contains the default operator when adding a new filter

- frontend/components/FieldString/FieldStringEdit.jsx
> Edit view: make links open in new window

- frontend/components/DocumentFilters/DocumentFilters.jsx
> Make Add filter popup respect default operator

- frontend/components/FieldNumber/FieldNumberEdit.jsx
> Allow negative and decimal numbers in Number field

- frontend/actions/documentsActions.js
- frontend/components/FieldString/FieldStringEdit.jsx
> Ensure only document objects are added to the selection

- frontend/components/FieldNumber/FieldNumberEdit.jsx
> Allow Number fields to be unset

- frontend/components/FieldString/FieldStringEdit.jsx
- frontend/components/RichEditor/RichEditor.jsx
- test/functional/features/articles/03_rich_text_test.js
- test/functional/features/articles/04_article_filter_test.js
- test/functional/pages/Article.js
Fixes the URL of the inline image select view when creating new documents.
> Fix URL of inline image select

- frontend/components/TextInput/TextInput.jsx
- frontend/containers/SignIn/SignIn.jsx
> Add autofocus to username field on sign-in page

- app/actions/apiActions.js
- app/containers/DocumentField/DocumentField.jsx
- app/containers/DocumentFilters/DocumentFilters.jsx
- package.json
- server/lib/get-data-for-token.js
- test/api/workspace/collections/1.0/cloud/collection.no-filterable-fields.json
- test/functional/features/field_testing/08_no_filterable_field_test.js
- test/functional/pages/Field.js
> Handle collections with no filterable fields

- app/containers/CollectionNav/CollectionNav.jsx
- dev-config/config.test.json
- package.json
- test/functional/pages/Article.js
> Fix collection nav sorting

- app/actions/documentActions.js
- app/components/RichEditor/RichEditor.jsx
- app/containers/DocumentField/DocumentField.jsx
- app/reducers/document.js
- app/views/ReferenceSelectView/ReferenceSelectView.jsx
Closes #749
Closes #750 
(I put these in one PR, because the bugs are truly minor)
> Fix rich editor bugs

- app/components/DocumentListController/DocumentListController.css
- app/components/EditInterface/EditInterface.css
- app/components/EditInterface/EditInterface.jsx
- app/components/SubNavItem/SubNavItem.css
- app/components/SubNavItem/SubNavItem.jsx
I go against the designs in that the dropdown is not fullscreen; I vaguely remember from a previous job that trying to prevent the page from scrolling when a dropdown/modal is showing creates problems in certain mobile browsers and it's a mare to make it work. It's up for discussion, though.
Changed the mobile filter dropdown in the same way.
> Reskin mobile document section navigation

- app/components/DocumentListController/DocumentListController.jsx
- app/components/FieldMedia/FieldMediaEdit.jsx
- app/components/Label/Label.css
- app/components/Label/Label.jsx
- app/components/Table/Table.jsx
- app/components/Table/TableHead.jsx
- app/lib/util/url.js
The 5 that are right now under stage 'QA/review' && type 'bug' in the project board
> Remove some minor bugs

- app/actions/appActions.js
- app/components/DocumentListController/DocumentListController.jsx
- app/components/EditInterface/EditInterface.jsx
- app/components/HeroMessage/HeroMessage.css
- app/components/Notification/Notification.css
- app/components/Notification/Notification.jsx
- app/edit-ui/src/components/Button/Button.css
- app/edit-ui/src/components/Select/Select.jsx
- app/views/DocumentListView/DocumentListView.css
- app/views/DocumentListView/DocumentListView.jsx
- app/views/HomeView/HomeView.css
- Change _Add filter_ button to _Apply_
- Show _Delete_ button on collection view even when no documents are selected
- Remove selection count from collection view
- Adjust styling of Home view (limit the width + add pink line on mobile)
- Show filters when document list is empty _and_ filters are applied
- Fix alignment of notifications
- Remove downward motion on button click
- Use native select element for document edit tabs on mobile
> Changes from creative review #1

- app/components/Table/Table.css
- app/components/Table/TableHeadCell.jsx
- app/containers/DocumentTableList/DocumentTableList.css
- app/containers/DocumentTableList/DocumentTableList.jsx
- app/lib/util/url.js
... + remove scaling animation on row select.
> Add new styling for table heading

- app/components/RichEditor/RichEditor.css
- app/components/RichEditor/RichEditor.jsx
- app/components/RichEditor/slateNodes.js
- app/components/RichEditor/slatePlugin.js
- app/components/RichEditor/slateRender.js
- app/components/RichEditor/utils.js
- package-lock.json
- package.json
Updates to slate-md-serializer v1.2.1 and makes changes to rendering and handling paragraphs and list items accordingly
TODO: 
- Implement indenting and deindenting
- Handle keys like Enter, Delete, Backspace properly in nested lists
> Change handling of paragraphs & nested lists in RE

- app/components/Fullscreen/Fullscreen.css
- app/components/RichEditor/RichEditor.css
- app/components/RichEditor/RichEditor.jsx
- app/components/RichEditor/slatePlugin.js
- app/components/RichEditor/slateSchemaRich.js
> Rich editor: list improvements & fullscreen fix

- app/components/RichEditor/slatePlugin.js
- package-lock.json
- test/functional/pages/Field.js
When the cursor is at the beginning of a paragraph inside a blockquote, unwrap the blockquote
> Implement blockquote unwrapping on bksp
