dadi/publish

dadi/frontend/actions/routerActions.js
dadi/frontend/lib/router.js
dadi/frontend/lib/util.js
dadi/frontend/middleware/router.js
dadi/frontend/reducers/router.js
dadi/frontend/views/DocumentList/DocumentList.jsx

This PR addresses the lack of support for query parameter changing with `preact-router`. 
Using the `router` method from `lib/router` you can now call basic routes as before, as well as update or override url parameters.
```javascript
// Basic route change
router({path: '/'})
// Change parameters
// Note that path will default to `window.location.pathname`
router({params: {foo: "bar"}})
// Append existing parameters with `Object.assign`
router({params: {foo: "bar", update: true}})
// Clear all parameters in the current route (not that useful)
router()
```
The other minor change is that now `state.router` has an extra parameter, `params`. This stores an Object of the query parameters:
```javascript
{
foo: "bar",
filters: {
email: "publish_wizard@dadi.co"
}
}
```

feat: routing method with query params

---

.gitignore
docs/components/Checkbox.md
docs/components/ElapsedTime.md
docs/components/FieldBoolean.md
docs/components/Label.md
frontend/actions/documentActions.js
frontend/actions/documentsActions.js
frontend/components/Checkbox/Checkbox.css
frontend/components/Checkbox/Checkbox.jsx
frontend/components/Dropdown/Dropdown.css
frontend/components/ElapsedTime/ElapsedTime.jsx
frontend/components/FieldBoolean/FieldBoolean.jsx
frontend/components/FieldString/FieldString.css
frontend/components/FieldString/FieldString.jsx
frontend/components/Label/Label.css
frontend/components/Label/Label.jsx
frontend/components/LoadingBar/LoadingBar.jsx
frontend/containers/App/App.jsx
frontend/containers/CollectionNav/CollectionNav.jsx
frontend/lib/app-config.js
frontend/reducers/api.js
frontend/views/DocumentEdit/DocumentEdit.css
frontend/views/DocumentEdit/DocumentEdit.jsx
frontend/views/DocumentList/DocumentList.jsx

This PR adds:
- Support for `Boolean` API fields (with the `FieldBoolean` component)
- Support for dropdowns (single and multiple) in `FieldString`
- Support for multiple APIs
- Collection nav now uses collection friendly name (`settings.description`) by default and slug as a fallback
- Minor performance fixes to `LoadingBar`

Additional field types and support for multiple APIs

---

frontend/lib/api-bridge-client.js

This PR adds throttling to API bridge calls, as per #32. It has a configurable number of maximum calls per second, and every time this limit is exceeded we "close the gate" on requests and only open it again once the flood of requests has stopped for a second.
When the limit is exceeded, API bridge calls return a Promise rejected with `API_CALL_QUOTA_EXCEEDED`.

Add throttling to API bridge calls

---

frontend/containers/DocumentEdit/DocumentEdit.jsx
frontend/containers/NotificationCentre/NotificationCentre.jsx
frontend/reducers/app.js
frontend/reducers/document.js

This PR addresses the issue outlined in #137. Fields only validate themselves once they have been interacted with OR when the user tries to save the document, and not when the page loads. This is to avoid seeing loads of error messages on the page before the user even starts working on the document.
However, previously we weren't actually blocking the save operation when validation errors occurred. We are now. So if you try to submit the form with a required field missing, the error messages will be flagged and the save button will be disabled.
(Again, sorry for the confusing diff caused by changing the order of functions within the container. As files start getting larger, I find it really helps to have things sorted in a meaningful way.)

Enforce validation before submit

---

frontend/containers/DocumentEdit/DocumentEdit.jsx
frontend/containers/DocumentList/DocumentList.jsx

This PR handles the on-fetch filtering of fields based on `publish.display.{view}`

perf: only load fields with display true

---

app/lib/controllers/session.js
docs/component-architecture.md
docs/components/FileUpload.md
docs/containers/DocumentList.md
frontend/actions/documentActions.js
frontend/actions/userActions.js
frontend/components/FieldImage/FieldImage.css
frontend/components/FieldImage/FieldImageEdit.jsx
frontend/components/FieldReference/FieldReferenceEdit.jsx
frontend/components/FieldString/FieldStringEdit.jsx
frontend/components/FieldString/FieldStringList.jsx
frontend/components/FileUpload/FileUpload.jsx
frontend/containers/DocumentList/DocumentList.jsx
frontend/containers/DocumentListToolbar/DocumentListToolbar.jsx
frontend/views/DocumentListView/DocumentListView.jsx

This PR implements #214, adding support for reference fields with multiple documents, based on the `settings.limit` property.
This is for non-media reference fields only — do we want to do the same for media fields, @mingard?

Add support for multi-document reference fields

---

app/lib/controllers/api-bridge.js
app/lib/controllers/session.js
app/lib/router/index.js
app/lib/router/routes/api-bridge.js
app/lib/router/routes/session.js
frontend/actions/userActions.js
frontend/containers/App/App.jsx

This PR addresses an issue where the passport authentication was not globally accessible and thus could not be used to block API requests for an unauthenticated user.

feat: make sessions global

---

frontend/views/DocumentListView/DocumentListView.jsx

This fixes an issue where selecting a reference document when creating a new document redirects to the wrong URL.

Use correct redirect link when selecting referenced documents

---

frontend/containers/DocumentListToolbar/DocumentListToolbar.jsx

This fixes an issue where pagination elements get an incorrect link when selecting referenced document.

Use correct pagination links when selecting reference document

---

docs/component-architecture.md
docs/components/DocumentFilter.md
docs/components/DocumentFilters.md
docs/components/FieldBooleanFilter.md
docs/components/FieldDateTimeFilter.md
docs/components/FieldNumberFilter.md
docs/components/FieldStringFilter.md
docs/components/TextInput.md
docs/containers/DocumentEditToolbar.md
docs/containers/SignIn.md
frontend/containers/DocumentEditToolbar/DocumentEditToolbar.jsx

This PR fixes #229. `batchActions()` doesn't seem to work well with asynchronous actions (to be further investigated), so for now I've made it so we're firing two separate actions. As a consequence, I've also reverted this file to bounded action creators.

Fix issue with "Save as new" action

---

frontend/components/Notification/Notification.css
frontend/components/Notification/Notification.jsx
frontend/containers/DocumentEdit/DocumentEdit.jsx
frontend/containers/NotificationCentre/NotificationCentre.jsx

This PR adds a `fadeAfterSeconds` setting to `NotificationCentre`, allowing notifications to enter a less prominent state after a period of time. This state can be styled with the class `notification-faded`.
Closes #225.

Add fadeAfterSeconds setting to NotificationCentre

---

package.json
test/mocks/request-promise.js
test/unit/lib/controllers/session.test.js

`request-promise` fails when another module tries to expose a `Request` prototype, which I'm assuming Jest does. To get around that, I've added a mock for that module — we don't want the test suite to be doing actual HTTP requests, so I'm sure the mocked module will be useful for other tests.
This closes #253.

Add mock for request-promise

---

frontend/components/TextInput/TextInput.jsx

This PR makes `TextInput` pass the value to textarea nodes using the correct `value` prop, so that the DOM is in sync with the VDOM.
Closes #287.

Change textarea to use value prop

---

frontend/containers/DocumentEditToolbar/DocumentEditToolbar.jsx
frontend/containers/ProfileEditToolbar/ProfileEditToolbar.jsx

The const `hasConnectionIssues` contained a duplication of the logic that sets const `hasValidationErrors`:
```js
const hasConnectionIssues = state.app.networkStatus !== Constants.NETWORK_OK
&& Object.keys(document.validationErrors)
.filter(field => document.validationErrors[field])
.length
const hasValidationErrors = validationErrors && Object.keys(validationErrors)
.filter(field => validationErrors[field])
.length
```
An error was being thrown because `hasConnectionIssues` did not contain a check for `validationErrors` before attempting to iterate it's keys which alerted me to the fact it did not need to contain the extra logic. `hasCollectionIssues` should only reflect whether the client is connected and not whether `validationErrors` exist.

fix: remove duplication that throws error

---

app/lib/models/collection.js
frontend/containers/DocumentEdit/DocumentEdit.jsx
frontend/containers/LazyLoader/LazyLoader.jsx
frontend/reducers/document.js

This PR addresses an issue with document unload, which causes document data to be cached in state after navigating away. 
To replicate the issue:
- add logging to the `fetchDocument` method in `DocumentEdit`. 
- navigate to a document
- navigate to another view
- navigate back to the same document
- observe that `fetchDocument` is not fired, as the state for `document` remains populated, with an idle status

fix: unload document on exit

---

app/config-schema.js
config/config.development.json.dist
config/config.production.json.dist
config/config.test.json
frontend/containers/App/App.jsx
test/unit/app/lib/controllers/app-config.test.js

Addresses an issue where Publish defaults on the server port, which is inaccurate an non-dependable when running behind a load balancer or proxy.
fixes: https://github.com/dadi/publish/issues/354

fix: use publicUrl to determine websocket connection

---

index.js
package.json

This PR adds a boot message using the @dadi/boot module. Looks a bit like this:
```
⠋ Starting @dadi/publish...
✔ Started @dadi/publish
@ 127.0.0.1:9999
┌──────────────────────────────────────────┐
│ DADI Publish - Publisher Name            │
┌──────────────┬───────────────────────────┐
│ Version      │ 1.0.5-beta                │
│ Node.js      │ 8.9                       │
│ Environment  │ development               │
└──────────────┴───────────────────────────┘
ℹ Documentation at https://docs.dadi.cloud
ℹ <CTRL> + C to shut down
▓▓▓▓▓  ▓▓▓▓▓▓▓
▓▓▓▓
▓▓▓▓▓▓▓    ▓▓▓▓
▓▓▓▓
▓▓▓▓▓▓▓
© 2018 DADI+ Limited (https://dadi.cloud)
All rights reserved.
```

Add DADI boot message

---

frontend/components/FieldString/FieldString.css
frontend/components/FieldString/FieldStringEdit.jsx
frontend/components/FieldString/FieldStringList.jsx

Turns string fields into links for inside the Publish interface, both in the edit view and list view. Useful for external services.
Closes #477 
Example schema (team collection on dadi.cloud)
```json
"twitter": {
"type": "String",
"required": false,
"label": "Twitter",
"publish": {
"section": "Details",
"placement": "sidebar",
"display": {
"edit": true,
"list": true,
"link": "https://twitter.com/{value}"
}
}
},
"linkedIn": {
"type": "String",
"required": false,
"label": "LinkedIn",
"publish": {
"section": "Details",
"placement": "sidebar",
"display": {
"edit": true,
"list": true,
"link": "https://linkedin.com/in/{value}"
}
}
},
"personalSite": {
"type": "String",
"required": false,
"label": "Personal site",
"publish": {
"section": "Details",
"placement": "sidebar",
"display": {
"edit": …
```

allow string fields to be links

---

frontend/containers/DocumentList/DocumentList.jsx

This PR addresses a small issue if you set a `Reference` field or `Media` field as the first displayed field in your API schema you are unable to click through from the list view (both those fields override the link).
It finds the first field of type `String` and appends the document link to that value, even if it's not in position `0`. If there are no `String` fields in the schema, it fallsback to position `0`

first string field takes preference as document link

---

frontend/components/Notification/Notification.css

Currently, notifications take up the full viewport width, meaning that it's impossible to click on any elements on the same horizontal position, even if they are not directly obstructed by the notification.
This PR fixes that.

Stop notification from obstructing full width

---

frontend/components/RichEditor/RichEditor.css
frontend/components/RichEditor/RichEditor.jsx
frontend/lib/local-storage.js

This PR handles the Return key on code blocks, preventing a new block from being created. Additionally, it also fixes an issue where the "Unsaved changes" dialog was being shown unnecessarily.
Closes #561.
Closes #620.

Handle Return key on code block + remove paragraph from list items

---

frontend/actions/apiActions.js
frontend/actions/documentActions.js
frontend/actions/documentsActions.js
frontend/components/ColorPicker/ColorPicker.jsx
frontend/components/DocumentTableList/DocumentTableList.jsx
frontend/components/FieldDateTime/FieldDateTimeEdit.jsx
frontend/components/FieldMedia/FieldMediaEdit.jsx
frontend/components/FieldMedia/FieldMediaItem.jsx
frontend/components/FieldReference/FieldReferenceEdit.jsx
frontend/components/FieldReference/FieldReferenceList.jsx
frontend/components/FieldString/FieldStringEdit.jsx
frontend/components/FileUpload/FileUpload.jsx
frontend/containers/DocumentEdit/DocumentEdit.jsx
frontend/containers/DocumentList/DocumentList.jsx
frontend/containers/MediaListController/MediaListController.jsx
frontend/lib/fields.js
frontend/reducers/document.js
frontend/views/DocumentEditView/DocumentEditView.jsx
frontend/views/DocumentListView/DocumentListView.jsx
frontend/views/MediaEditView/MediaEditView.jsx
frontend/views/ReferenceSelectView/ReferenceSelectView.jsx

When a field of type `Media` has a `validation.mimeTypes` array defined, any filed dropped into the field that doesn't respect the validation rule triggers an error, displayed in a similar fashion to the errors generated by other field types, as shown by the screenshot below.
Closes #543.
Prevent the `minLength` validation rule from blocking a save when the field is empty.
Closes #419.
Refactor the way the document edit and document list views compute the list of fields that should be displayed, so that the `publish.display` properties are taken into account if and only if at least one of the fields in the collection has them. If not, all fields are displayed by default.
Refactor the action for saving documents in order to process not only fields of type `Reference` but also `Media`.
Make …

Various fixes

---

frontend/components/RichEditor/RichEditor.jsx

Preventing an infinite loop when signing out whilst on a document edit view with a RichEditor component.

Normalise empty values in RichEditor

---

app/config-schema.js
app/config.js

This PR removes most of the `server` config block from the front-end and adds some validation rules to the `apis` block, stopping the application if the legacy `credentials` block is found.

Improve config validation

---

frontend/components/BulkActionSelector/BulkActionSelector.css
frontend/components/BulkActionSelector/BulkActionSelector.jsx
frontend/components/Button/Button.css
frontend/components/Button/Button.jsx
frontend/components/DocumentFilters/DocumentFilters.css
frontend/components/DocumentListController/DocumentListController.css
frontend/components/DocumentListController/DocumentListController.jsx
frontend/components/DocumentListToolbar/DocumentListToolbar.css
frontend/components/DocumentListToolbar/DocumentListToolbar.jsx
frontend/components/Paginator/Paginator.css
frontend/components/Paginator/Paginator.jsx
frontend/components/Toolbar/Toolbar.css
frontend/components/Toolbar/ToolbarTextInput.jsx
frontend/containers/App/App.jsx
frontend/views/DocumentListView/DocumentListView.jsx
frontend/views/MediaListView/MediaListView.jsx

🔍  Available for testing at http://publish-feature-mobile-improvements.eb.dev.dadi.technology/
---
Fixes an issue where, after signing in, the scroll position made it so that the nav menu wasn't visible unless the user scrolled up.
Fixes an issue where not having enough content on the table view pushed the bottom toolbar to the middle of the screen. Now it's anchored to the bottom of the screen.
Reduces the size of the "Create new" button, making it on the same line as the filters and therefore reducing the amount of vertical space used.
For space optimisation, simplifies the pagination elements on the bottom toolbar by:
1. Removing the individual page numbers in favour of the Prev/Next buttons
1. Removing the "Showing x of y" label in favour of a new "go to page" input element, where a …

Various improvements for mobile

---

frontend/components/ReferenceSelectHeader/ReferenceSelectHeader.jsx
frontend/containers/DocumentField/DocumentField.jsx
frontend/views/ReferenceSelectView/ReferenceSelectView.jsx

... and an issue with the "Return to document" button link on the reference select view.

Fix issues with Reference field validation

---

frontend/components/EditInterface/EditInterface.css

This PR removes `position: sticky;` from the sidebar on the document edit view, to make scrolling easier.
/cc @josephdenne

Make sidebar not sticky

---

app/components/FieldString/FieldStringList.jsx

Closes #688 
String values in list views are truncated with an ellipsis. This PR trims any punctuation marks which appear immediately before the ellipsis.

Remove trailing punctuation from truncated strings on list views

---

app/components/Label/Label.css
app/components/Label/Label.jsx

Closes #646 
Flexbox ftw!
For clarity: for the `.header` I used the pattern of 
```css
.someElement {
margin: -x 0 0 -y;
}
.someElement > div {
margin: x 0 0 y;
}
```
which puts a gutter between the children elements without changing the outer margins of the cointaining element.

Fix overlapping labels on fields

---

app/containers/App/App.jsx
app/containers/Header/Header.jsx
app/reducers/api.js
app/reducers/index.js
app/views/ErrorView/ErrorView.jsx
package-lock.json
package.json
server/routes/config.js

Closes #727
Storing the access token from one instance of API in cookies and sending it over to another instance would cause trouble.
I now realize this, of course, only happens because both my local instance and the `dadi.technology` instance of API happen to have the same (default) JWT secret, which would never happen in production, but oh well.
Removed the unused `api` reducer and some related dead code.

Fix errors caused by switching between APIs

---

app/components/FieldReference/FieldReference.css
app/components/FieldReference/FieldReferenceEdit.jsx
app/components/FieldReference/FieldReferenceList.jsx

Closes #685 
A quick fix to avoid breaking UI for now; ideally a more substantial fix would refactor the component to make the CSS a bit less unwieldy, but I expect an overhaul of the UI at some point in not so distant future, so I don't wanna invest too much time into this.

Fix overflow in reference field

---

app/views/ReferenceSelectView/ReferenceSelectView.jsx
test/functional/pages/Article.js
test/functional/pages/Field.js

Closes #739 
I changed the text of the button from "add selected document(s)" to "save selection", because you're not always *adding* documents. What do you think?

Allow deselecting all references

---

app/components/TextInput/TextInput.jsx
app/components/TextInputWithDatePicker/TextInputWithDatePicker.jsx
app/lib/datetime.js

I put a few fixes together into a single PR, because they're tiny.
1. **When manually typing a date into a date input field, the app would go into an infinite loop and freeze.**
1. When manually typing the date, after going from an invalid value to a valid one, the cursor would jump to the end of the input.
1. The date input field would not allow deleting the value completely.
Also, I fixed an unrelated potential bug in `TextInput` (in fortunately otherwise unused code):
```javascript
const {oldHeightType} = oldProps
```
changed to
```javascript
const {heightType: oldHeightType} = oldProps
```

Fix a few minor datetime bugs

---

app/components/RichEditor/RichEditor.jsx
app/components/RichEditor/RichEditorLink.css
app/components/RichEditor/RichEditorLink.jsx

Closes #746 
Displays the link input above the beginning of the link, unless that would go above the top of the editor, in which case it displays the link input below the beginning of the link.

Fix position of link input in rich editor

---

app/components/DocumentTableList/DocumentTableList.jsx
app/views/ReferenceSelectView/ReferenceSelectView.jsx
test/functional/pages/Article.js

Fix sorting docs in ReferenceSelectView

---

app/components/ReferenceSelectHeader/ReferenceSelectHeader.jsx
app/views/ReferenceSelectView/ReferenceSelectView.jsx
package-lock.json
package.json
test/functional/pages/Article.js
test/functional/pages/Field.js
test/functional/pages/Media.js

This will have to be rewritten to fix merge conflict with #762, but just putting it out here anyway

Clear selection when leaving select view
